<?php
return array(
	'album'=>'Album',
	'banner'=>'Banner',
	'setting'=>'Cấu hình',
	'register'=>'Đơn đăng kí',
	'order'=>'Đơn hàng',
	'qa'=>'Hỏi đáp',
	'image'=>'Image',
	'keyword'=>'Keyword',
	'contact'=>'Liên hệ',
	'menu'=>'Menu',
	'language'=>'Ngôn ngữ',
	'role'=>'Quản lý quyền',
	'product'=>'Sản phẩm',
	'news'=>'Tin tức',	
	'support'=>'Tư vấn viên',
	'recruitment'=>'Tuyển dụng',
	'staticPage'=>'Trang tĩnh',
	'user'=>'User',
	'app'=>'Ứng dụng',
	'galleryVideo'=>'Video',	
);